export const GAME_SETTINGS = {
    width: 800,
    height: 700,
    paddingX: 30,
    firstCarColor: '#d1191f',
    secondCarColor: '#ffc841',
    trailWidth: 25,
    carsStartGap: 320,
    carsStartBottom: 30,
    carAnimationSpeed: 110,
    carIntersectWithMulti: 1.2,
    failHideDelay: 1.20,
    inactivityTime: 20000,
    handOneMoveDuration: 1.2,
    handStartYOfsset: -30,
    spotsLength: 4,
    spotHeightMulti: 0.3,
    spotsGap: 20,
    lineRenderY: 1500,
    buttonURL: 'https://roasup.com/',
    logoWidthPercent: 0.6,
    logoHeightPercent: 0.4,
    Eps: 0.00001,
  }